### ISSUE TITLE
Node16 is deprecated, upgrade to node20

### ISSUE THREAD

**Issue by marcodicro-dp** [kaisugi/action-regex-match#1]
Workflow warning:
<img width="1531" alt="image" src="https://github.com/kaisugi/action-regex-match/assets/121044623/1859a3b3-daeb-4750-a05a-63483dad131a">

**Comment by kaisugi** [comment]
released [v1.0.1](https://github.com/kaisugi/action-regex-match/releases/tag/v1.0.1) that uses Node.js v20!

**Comment by marcodicro-dp** [comment]
Works great now without any warnings. Thanks!!!
